mappings:
  WebpackPageControllerExtension: Sunnysideup\WebpackRequirementsBackend\Control\WebpackPageControllerExtension
  Requirements_Backend_For_Webpack: Sunnysideup\WebpackRequirementsBackend\View\Requirements_Backend_For_Webpack
