mappings:
  WebpackPageControllerExtension: Sunnysideup\WebpackRequirementsBackend\Control\WebpackPageControllerExtension
  RequirementsBackendForWebpack: Sunnysideup\WebpackRequirementsBackend\View\RequirementsBackendForWebpack
