<?php

declare(strict_types=1);

namespace Sunnysideup\WebpackRequirementsBackend\View;

use SilverStripe\Admin\LeftAndMain;
use SilverStripe\Control\Controller;
use SilverStripe\Control\Director;
use SilverStripe\Core\Config\Config;
use SilverStripe\Core\Config\Configurable;
use SilverStripe\Core\Convert;
use SilverStripe\Core\Injector\Injector;
use SilverStripe\Dev\TaskRunner;
use SilverStripe\View\Requirements_Backend;
use SilverStripe\View\SSViewer;
use Sunnysideup\WebpackRequirementsBackend\Api\Configuration;
use Sunnysideup\WebpackRequirementsBackend\Api\NoteRequiredFiles;

class RequirementsBackendForWebpack extends Requirements_Backend
{
    use Configurable;

    /**
     * Whether to add caching query params to the requests for file-based requirements.
     * Eg: themes/myTheme/js/main.js?m=123456789. The parameter is a timestamp generated by
     * filemtime. This has the benefit of allowing the browser to cache the URL infinitely,
     * while automatically busting this cache every time the file is changed.
     */
    protected bool $suffix_requirements = false;

    /**
     * Whether to combine CSS and JavaScript files.
     */
    protected bool $combined_files_enabled = false;

    /**
     * Force the JavaScript to the bottom of the page, even if there's a script tag in the body already.
     */
    protected bool $force_js_to_bottom = true;

    /**
     * e.g. /app/javascript/test.js.
     * see: vendor/sunnysideup/webpack_requirements_backend/_config/config.yml
     */
    private static array $files_to_ignore = [];

    private static array $files_starts_with_ignore = [];

    /**
     * e.g. "google.com", "fonts.googleapis.com", "use.fontawesome.com".
     */
    private static array $domains_to_ignore = [];

    private static array $urls_to_exclude = [];

    private static array $classes_to_exclude = [
        // 'SilverStripe\\UserForms\\Control\\UserDefinedFormController',
    ];

    /**
     * @param string $content
     *
     * @return string HTML content
     */
    public function includeInHTML($content)
    {
        if (self::is_themed_request()) {
            //=====================================================================
            // start copy-ish from parent class

            $requirementsCSSFiles = [];
            $requirementsJSFiles = [];

            // Combine files - updates $this->javascript and $this->css
            $this->processCombinedFiles();
            $isDev = Director::isDev();
            $toIgnore = $this->Config()->get('files_to_ignore');
            foreach ($this->getJavascript() as $file => $params) {
                $ignore = in_array($file, $toIgnore, true)
                    || $this->shouldDomainBeIgnored($file)
                    || $this->shouldStartsWithBeIgnored($file);
                if ($ignore) {
                    if ($isDev) {
                        $path = Convert::raw2xml($this->pathForFile($file));
                        if ($path) {
                            $requirementsJSFiles[$path] = $path . '__' . json_encode($params);
                        }
                    }
                } else {
                    $this->unsetJavascript($file);
                }
            }

            foreach ($this->getCSS() as $file => $params) {
                $ignore = in_array($file, $toIgnore, true)
                    || $this->shouldDomainBeIgnored($file)
                    || $this->shouldStartsWithBeIgnored($file);
                if ($ignore) {
                    if ($isDev) {
                        $path = Convert::raw2xml($this->pathForFile($file));
                        if ($path) {
                            $requirementsCSSFiles[$path] = $path . '__' . json_encode($params);
                        }
                    }
                } else {
                    $this->unsetCSS($file);
                }
            }
            //copy files ...
            if (NoteRequiredFiles::can_save_requirements()) {
                //css
                foreach ($requirementsCSSFiles as $cssFile) {
                    Injector::inst()->get(NoteRequiredFiles::class)->noteFileRequired($cssFile, 'css');
                }

                //js
                foreach ($requirementsJSFiles as $jsFile) {
                    Injector::inst()->get(NoteRequiredFiles::class)->noteFileRequired($jsFile, 'js');
                }
            }
        }

        return parent::includeInHTML($content);
    }

    public static function is_themed_request(): bool
    {
        if (Config::inst()->get(SSViewer::class, 'theme_enabled') && Config::inst()->get(Configuration::class, 'enabled') && Controller::has_curr()) {
            $controller = Controller::curr();
            foreach (Config::inst()->get(static::class, 'classes_to_exclude') as $class) {
                if ($controller instanceof $class) {
                    return false;
                }
            }
            return ! $controller instanceof LeftAndMain && ! $controller instanceof TaskRunner;
        }

        return false;
    }

    /**
     * required! not sure why....
     */
    public function deleteAllCombinedFiles()
    {
        $combinedFolder = $this->getCombinedFilesFolder();
        if ($combinedFolder) {
            // @var GeneratedAssetHandler|null $assetHandler
            $assetHandler = $this->getAssetHandler();
            if ($assetHandler) {
                $assetHandler->removeContent($combinedFolder);
            }
        }
    }

    protected function shouldDomainBeIgnored($file): bool
    {
        $toIgnoreDomains = $this->Config()->get('domains_to_ignore');
        foreach ($toIgnoreDomains as $domain) {
            if (str_contains($file, '//' . $domain . '/')) {
                return true;
            }
        }
        return false;
    }

    protected function shouldStartsWithBeIgnored($file): bool
    {
        $startsWith = $this->Config()->get('files_starts_with_ignore');
        foreach ($startsWith as $start) {
            if (strpos($file, $start) === 0) {
                return true;
            }
        }
        return false;
    }
}
