---
Name: webpack_requirements_backend
---
SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - Sunnysideup\WebpackRequirementsBackend\Control\WebpackPageControllerExtension

Sunnysideup\WebpackRequirementsBackend\View\RequirementsBackendForWebpack:
  domains_to_ignore:
    - "fonts.googleapis.com"
    - "maps.googleapis.com"
  files_starts_with_ignore:
    - vendor/silverstripe
    - vendor/undefinedoffset/silverstripe-nocaptcha
    - vendor/lekoala/silverstripe-debugbar
    - vendor/atwx/silverstripe-altcha-spamprotection
    - vendor/sunnysideup/elemental-edit-me-button
    - vendor/undefinedoffset/silverstripe-nocaptcha
    - "https://www.google.com/recaptcha/api.js"

  # files_to_ignore:
    #js
    # css
